# Generated by Django 6.0.2 on 2026-05-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrucitonStep',
            new_name='InstructionStep',
        ),
    ]
