# Generated by Django 6.0.2 on 2026-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_instrucitonstep_instructionstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionstep',
            name='step_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cookTime',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='prepTime',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='servings',
            field=models.PositiveIntegerField(),
        ),
    ]
