# Generated by Django 6.0.2 on 2026-05-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipes_cooktime_alter_recipes_preptime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cookTime',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='prepTime',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='servings',
            field=models.PositiveIntegerField(),
        ),
    ]
