# Generated by Django 6.0.2 on 2026-05-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipes_cooktime_alter_recipes_preptime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fingerprint',
            field=models.CharField(default='TESTING', max_length=100, unique=True),
        ),
    ]
