# Generated by Django 6.0.2 on 2026-05-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_ingredient_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fingerprint',
            field=models.CharField(default='TESTING', max_length=100),
        ),
    ]
