# Generated by Django 6.0.2 on 2026-05-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredient_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='fingerprint',
        ),
    ]
