# Generated by Django 6.0.2 on 2026-05-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_ingredient_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
