# Generated by Django 6.0.2 on 2026-05-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_ingredient_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fingerprint',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
