# Generated by Django 6.0.2 on 2026-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredient_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cookTime',
            field=models.PositiveIntegerField(default=0, help_text='Cooking time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='prepTime',
            field=models.PositiveIntegerField(default=0, help_text='Preparation time in minutes'),
        ),
    ]
